### ISSUE TITLE
Bug report: continues processing the clipboard in a loop

### ISSUE THREAD

**Issue by IrreverentZuss** [cylin2000/clipboard_monitor#1]
Hello there, hope you are alright!

Is there a way to solve the loop so that the update on keyboard get called just once, when something new is copied? You have done a very nice writing by the way but it lucks commentary!

Thanks

**Comment by caiyunlin** [comment]
Hi @IrreverentZuss , thank you very much for the feedback. 
I have tested the lib, the lib will not loop trigger the function, it's triggered by win32 WM_CLIPBOARDUPDATE event. 
Would you provide the detailed information (screenshots/logs) for the loop, thanks.

**Comment by IrreverentZuss** [comment]
If the lib is fine, can you please run the python program I uploaded in my stash, so you can see your self what I mean loop. The thing is that, after I found out that there is a loop going on, I run your example with the file, text and image functions and looping was the same. So if there is no loop with the lib and there is no loop with my script, there is something really wrong with the python setup in my computer ^^

**Comment by caiyunlin** [comment]
I downloaded your code and I added one line in your code, I can see the clipboard_monitor.on_text only executed once, but your code loop some times. 

==code==
```
def URL2FhdImage(url):

		print("got text "+url) # Added this line

		# Defining lists with the usual picture attributes of URLs.
		MMKw = ['width=640','width=324','width=160','width=79',]
		BAw = ['width=1533','width=1022','width=58']	
```
==result==
```
Listen to the copied photo URLS from BoatAround or MMK...



got text portal.booking-manager.com
I just got the MMK link...

***Processing***

****The image already exist****

I just got the MMK link...

***Processing***

****The image already exist****

I just got the MMK link...

***Processing***

****The image already exist****

I just got the MMK link...

***Processing***

****The image already exist****


```

====
should be the for curWidth in MMKw looped some times
```
		if MMK in url:
			# For every current width in the list "MMK".
			for curWidth in MMKw:
				# If the defined domain and the current width from the list are contained in the URL.
				if curWidth and MMK in url:
```

**Comment by IrreverentZuss** [comment]
Hello there,

That was really a bulls-eye answer and made me think that I never set a break over there! 
Thank you very much! I hope to collaborate with you sometime!

Wish you have a good summer season!

Panos
